spring:
    datasource:
#      url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#      username: root
#      password: 1234
      url: jdbc:mysql://awseb-e-cvsbqpwcpb-stack-awsebrdsdatabase-xvipuqbgigke.cl4y402o40ld.ap-southeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul/board?useSSL=false&serverTimezone=Asia/Seoul
      username: fastcam
      password: 3819abcd
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
